### ISSUE TITLE
All output pngs are blank

### ISSUE THREAD

**Issue by david-y-zhang** [data-forge/data-forge-plot-examples#1]
I download these examples, run on my computer, but all the output pngs and webs are black, nothing. My environment: MacOS.

And, there are some warnings like below, I do not know wether it are related:

![image](https://user-images.githubusercontent.com/68144333/87219976-8d362980-c392-11ea-8604-a333852c9f55.png)

**Comment by david-y-zhang** [comment]
Sorry for the last screenshot. Please see this one:

![image](https://user-images.githubusercontent.com/68144333/87219990-bce53180-c392-11ea-9267-f982819ce128.png)

**Comment by ashleydavis** [comment]
Hi David,

Thanks for reporting this issue. 

Just tested this and it works on Windows, but not on MacOS.

I'll look into it as soon as I can.

**Comment by ashleydavis** [comment]
Hi David,

I've fixed this issue for MacOS.  Please get latest code and try it again.

Thank you so much for reporting the issue.
